[package]
name = "rust-scanner"
version = "0.1.0"
edition = "2021"
authors = ["Noah Taheij <noah@taheij.nl>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
clap = "2.33"
